tasks:
  - init: |
      sudo apt update && sudo apt install -y postgresql postgresql-contrib
      sudo service postgresql start
      createdb -U postgres holiday_planner || true
    command: |
      sudo service postgresql start
      python3 -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
      python3 run.py runserver

env:
  DATABASE_URL: postgresql://postgres:postgres@localhost:5432/holiday_planner
  SECRET_KEY: devsecret
