# .gitpod.yml

tasks:
  - name: Setup PostgreSQL and Python environment
    init: |
      sudo apt update && sudo apt install -y postgresql postgresql-contrib python3-pip
      sudo service postgresql start
      sudo -u postgres psql -c "CREATE USER dev WITH PASSWORD 'devpass';"
      sudo -u postgres psql -c "CREATE DATABASE holiday_planner OWNER dev;"
      pip3 install -r requirements.txt
    command: |
      echo "PostgreSQL and environment are ready!"
      python3 run.py runserver

ports:
  - port: 5000
    onOpen: open-preview

env:
  DATABASE_URL: postgresql://myuser:masteRh0512.@localhost:5433/mydb
