version: '3.8'
services:
  db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: masteRh0512.
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
